# Generated by Django 3.2 on 2021-04-27 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataDocumentName', models.CharField(max_length=1000)),
                ('DataDocumentType', models.CharField(max_length=10)),
                ('DataDocumentFile', models.FileField(max_length=1000, upload_to='DocumentFile/')),
                ('DataDocumentAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataDocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataDocumentFile', models.FileField(upload_to='DocumentFile/')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataDocumentContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataDocumentSentence', models.CharField(max_length=500)),
                ('DataDocumentSentenceLength', models.IntegerField(default=0)),
                ('DataDocumentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileComponent.datadocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='datadocumentcontent',
            index=models.Index(fields=['DataDocumentNo', 'DataDocumentSentence'], name='DataDocumentNo_idx'),
        ),
        migrations.AddIndex(
            model_name='datadocumentcontent',
            index=models.Index(fields=['DataDocumentSentence'], name='DataDocumentSentence_idx'),
        ),
    ]