# Generated by Django 3.2 on 2021-04-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileComponent', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('CREATE FULLTEXT INDEX customer_fulltext_idx ON filecomponent_datadocumentcontent(DataDocumentSentence)',)
    ]
