# Generated by Django 3.1.4 on 2021-03-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreprocessingComponent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadocumentcontent',
            name='DataDocumentNo',
        ),
        migrations.DeleteModel(
            name='DataDocument',
        ),
        migrations.DeleteModel(
            name='DataDocumentContent',
        ),
    ]
